/**
 * Datos del modelo de controles de seguridad.
 * Cada control incluye: amenaza, política, decisión, fortaleza, limitación y riesgo residual.
 * Este es el núcleo pedagógico: Amenaza → Control → Política → Decisión → Riesgo Residual.
 */
export const CONTROL_MATRIX = [
  {
    id: 'eslint',
    name: 'ESLint',
    category: 'Calidad',
    type: 'Preventivo / Detectivo',
    stage: 'Desarrollo / CI',
    controlType: 'quality',
    threat: 'Defectos de codificación, inconsistencias, algunos patrones inseguros a nivel de código',
    input: 'Código fuente JavaScript',
    technique: 'Análisis estático de código (AST)',
    output: 'Lista de errores y advertencias con ubicación',
    policy: 'La presencia de errores de lint hace que el job retorne exit code ≠ 0',
    decision: 'PASS / FAIL',
    strength: 'Rápido, automatizable, detiene cambios con calidad insuficiente antes del merge',
    limitation: 'No es un scanner de seguridad completo. Las reglas dependen de la configuración elegida.',
    residualRisk: 'Vulnerabilidades de lógica y patrones no cubiertos por las reglas configuradas persisten.',
  },
  {
    id: 'tests',
    name: 'Pruebas Automatizadas',
    category: 'Pruebas',
    type: 'Detectivo',
    stage: 'CI',
    controlType: 'testing',
    threat: 'Regresiones funcionales, comportamiento inesperado no detectado antes del merge',
    input: 'Código fuente + suites de prueba',
    technique: 'Ejecución de casos de prueba definidos por el equipo',
    output: 'Resultados de ejecución: pruebas pasadas / fallidas',
    policy: 'Un test fallido hace que el job retorne exit code ≠ 0',
    decision: 'PASS / FAIL',
    strength: 'Valida el comportamiento esperado de forma repetible y automatizable',
    limitation: 'No prueban seguridad. Solo verifican lo que el test explícitamente cubre.',
    residualRisk: 'Comportamiento no cubierto por los tests, incluyendo casos borde y vectores de ataque.',
  },
  {
    id: 'sca',
    name: 'SCA — npm audit',
    category: 'SCA',
    type: 'Detectivo + Gate',
    stage: 'CI',
    controlType: 'sca',
    threat: 'Componentes de terceros con vulnerabilidades conocidas introducidos como dependencias',
    input: 'package-lock.json / árbol de dependencias completo',
    technique: 'Correlación con bases de datos de vulnerabilidades conocidas (NVD, GitHub Advisory Database)',
    output: 'Hallazgos de vulnerabilidades con severidad, CVE y paquete afectado',
    policy: 'Severidad HIGH o CRITICAL → job falla (exit code ≠ 0)',
    decision: 'ALLOW / BLOCK',
    strength: 'Rápido, automatizable, basado en inteligencia de vulnerabilidades conocidas y documentadas',
    limitation: 'Solo detecta lo que ya está en la base de datos. Zero-days no son detectados.',
    residualRisk: 'Vulnerabilidades zero-day, paquetes maliciosos sin CVE registrado, falsos negativos.',
  },
  {
    id: 'sast',
    name: 'SAST — CodeQL',
    category: 'SAST',
    type: 'Detectivo + Gate',
    stage: 'CI',
    controlType: 'sast',
    threat: 'Patrones de código potencialmente inseguros: XSS, inyección, flujos de datos peligrosos',
    input: 'Código fuente completo del repositorio',
    technique: 'Análisis de flujo de datos (taint tracking), AST, graph queries sobre el código',
    output: 'Alertas de seguridad con ubicación, severidad y descripción del flujo peligroso',
    policy: 'Hallazgo de alta severidad genera alerta en GitHub Security; puede bloquear el PR',
    decision: 'ALLOW / BLOCK',
    strength: 'Analiza el código sin ejecutarlo. Detecta flujos de datos peligrosos entre fuentes y sumideros.',
    limitation: 'Falsos positivos y falsos negativos posibles. Depende del query pack y la estructura del código.',
    residualRisk: 'Vulnerabilidades de lógica, problemas de diseño y patrones no cubiertos por las queries.',
  },
  {
    id: 'secret-scanning',
    name: 'Secret Scanning',
    category: 'Secretos',
    type: 'Preventivo / Detectivo',
    stage: 'Commit / Push',
    controlType: 'secrets',
    threat: 'Exposición de credenciales, tokens de API y secretos en el historial del repositorio',
    input: 'Commits y contenido del repositorio en cada push',
    technique: 'Reconocimiento de patrones de proveedores de secretos conocidos',
    output: 'Alertas de secretos detectados; push bloqueado si Push Protection está activo',
    policy: 'Secreto detectado → push bloqueado (Push Protection) o alerta generada para revisión',
    decision: 'ALLOW / BLOCK',
    strength: 'Puede prevenir la exposición de credenciales antes de que lleguen al historial público',
    limitation: 'Depende del proveedor, los patrones configurados y el plan de GitHub.',
    residualRisk: 'Secretos con formato no reconocido, secretos en archivos binarios o no monitoreados.',
  },
  {
    id: 'code-review',
    name: 'Revisión de Código',
    category: 'Gobernanza',
    type: 'Preventivo / Detectivo',
    stage: 'Pull Request',
    controlType: 'governance',
    threat: 'Cambios maliciosos, errores de lógica, problemas de diseño no detectables automáticamente',
    input: 'Diff completo del Pull Request',
    technique: 'Inspección manual por un revisor humano con contexto del sistema',
    output: 'Aprobación o solicitud de cambios con comentarios',
    policy: 'Aprobación requerida antes del merge (configurada en Branch Protection)',
    decision: 'APROBAR / RECHAZAR',
    strength: 'Revisión de lógica, contexto de negocio y diseño que los scanners automáticos no cubren',
    limitation: 'El error humano persiste. La fatiga del revisor es un riesgo real.',
    residualRisk: 'Errores de revisión, fatiga del revisor, cambios maliciosos bien camuflados.',
  },
  {
    id: 'branch-protection',
    name: 'Branch Protection',
    category: 'Gobernanza',
    type: 'Preventivo',
    stage: 'Merge',
    controlType: 'governance',
    threat: 'Push directo a main, merge sin controles, evasión forzada de checks de seguridad',
    input: 'Configuración de la rama + estado de los required status checks',
    technique: 'Enforcement de políticas a nivel de rama antes de permitir el merge',
    output: 'Merge permitido o bloqueado según el estado de los checks',
    policy: 'Merge bloqueado hasta que los required checks pasen y la revisión sea aprobada',
    decision: 'ALLOW / BLOCK',
    strength: 'Hace obligatoria la ejecución de los controles antes de cada merge en la rama protegida',
    limitation: 'Solo es efectiva si está bien configurada. Los administradores pueden eludirla.',
    residualRisk: 'Misconfiguraciones, cuentas con privilegios de admin que eluden la protección.',
  },
  {
    id: 'least-privilege',
    name: 'Least Privilege',
    category: 'Control de Acceso',
    type: 'Preventivo',
    stage: 'Pipeline',
    controlType: 'access',
    threat: 'Radio de impacto excesivo si una Action o workflow es comprometido o malicioso',
    input: 'Declaración explícita de permisos en el workflow YAML',
    technique: 'Restricción de permisos del GITHUB_TOKEN al mínimo necesario para el job',
    output: 'Alcance limitado del GITHUB_TOKEN durante la ejecución del workflow',
    policy: 'permissions: contents: read — solo los permisos mínimos requeridos por el job',
    decision: 'LIMITAR',
    strength: 'Reduce el impacto potencial si una Action comprometida intenta abusar del token',
    limitation: 'Una configuración incorrecta puede conceder más permisos de los necesarios.',
    residualRisk: 'Los permisos mínimos necesarios aún representan riesgo si el workflow es comprometido.',
  },
  {
    id: 'dependabot',
    name: 'Dependabot',
    category: 'SCA / Mantenimiento',
    type: 'Preventivo',
    stage: 'Repositorio',
    controlType: 'sca',
    threat: 'Dependencias desactualizadas acumulando vulnerabilidades conocidas con el tiempo',
    input: 'Árbol de dependencias del repositorio monitoreado continuamente',
    technique: 'Monitoreo de nuevas versiones y creación automática de PRs de actualización',
    output: 'Pull Requests automáticos para actualizar dependencias con vulnerabilidades o nuevas versiones',
    policy: 'Crea PRs automáticos; los PRs pasan por CI antes de ser considerados para merge',
    decision: 'PR / ALERTA',
    strength: 'Mantiene las dependencias actualizadas de forma sistemática y automatizada',
    limitation: 'Automatización ≠ Confianza. Las actualizaciones también pueden introducir cambios inesperados o riesgos de supply chain.',
    residualRisk: 'Un PR de Dependabot comprometido (supply chain attack) podría introducir código malicioso.',
  },
  {
    id: 'deploy',
    name: 'Despliegue — GitHub Pages',
    category: 'CD',
    type: 'Procedimental',
    stage: 'Deploy',
    controlType: 'governance',
    threat: 'Despliegue de artefactos no validados o comprometidos a producción',
    input: 'Artefacto validado generado desde la rama main protegida',
    technique: 'CD desde rama protegida usando identidad verificada (OIDC) y workflow dedicado',
    output: 'Aplicación publicada en GitHub Pages accesible públicamente',
    policy: 'El despliegue solo ocurre desde main, después de que todos los checks del CI pasan',
    decision: 'DEPLOY / BLOCK',
    strength: 'Separa el proceso de validación (CI) del proceso de publicación (CD)',
    limitation: 'La seguridad del despliegue depende de lo que haya pasado antes en el pipeline.',
    residualRisk: 'Vulnerabilidades que pasaron todos los controles configurados pero no fueron detectadas.',
  },
];

export function getControlDetails(controlId) {
  return CONTROL_MATRIX.find(c => c.id === controlId) ?? null;
}

export function getBlastRadius(mode) {
  if (mode === 'least-privilege') {
    return {
      mode: 'least-privilege',
      label: 'Least Privilege',
      permissionsDisplay: 'permissions:\n  contents: read',
      permissions: { contents: 'read' },
      impact: [
        'Puede leer el contenido del repositorio requerido por el job.',
        'Capacidad limitada para modificar recursos del repositorio.',
        'Una Action comprometida no puede crear releases ni modificar ramas protegidas.',
      ],
      severity: 'limited',
      description: 'El workflow tiene solo los permisos mínimos necesarios. El blast radius de una Action comprometida es limitado.',
    };
  }
  return {
    mode: 'excessive',
    label: 'Permisos Excesivos',
    permissionsDisplay: 'permissions: write-all',
    permissions: 'write-all',
    impact: [
      'Puede modificar potencialmente recursos del repositorio.',
      'Puede alterar releases, issues o contenido del repositorio.',
      'El impacto potencial depende de los recursos disponibles y la configuración del repositorio.',
    ],
    severity: 'high',
    description: 'El workflow tiene permisos amplios. Una Action comprometida tiene mayor alcance potencial sobre los recursos del repositorio.',
  };
}
