/**
 * src/labs.js
 * 10 lab definitions for the sequential lab flow.
 */

export const LABS = [
  {
    index: 0,
    labNumber: 1,
    concept: 'Pipeline CI/CD',
    title: 'Ejecuta tu primer pipeline seguro',
    description: 'Selecciona el escenario "Construcción Exitosa" y ejecuta el pipeline. Observa cómo el código pasa por cada etapa hasta producción.',
    interactiveKey: 'pipeline',
    scenarioToRun: 'healthy',
    lockHint: 'Ejecuta el escenario "Construcción Exitosa" para desbloquear la pregunta.',
    requiredInteractions: ['pipeline-run-healthy'],
    questionId: 'lab1-green-pipeline',
    maxPoints: 8,
  },
  {
    index: 1,
    labNumber: 2,
    concept: 'Security Gate — SCA',
    title: 'Observa cómo SCA bloquea el pipeline',
    description: 'Selecciona el escenario "Dependencia Vulnerable" y ejecuta el pipeline. Observa qué le ocurre a las etapas posteriores a SCA cuando falla.',
    interactiveKey: 'pipeline',
    scenarioToRun: 'vulnerable-dependency',
    lockHint: 'Ejecuta el escenario "Dependencia Vulnerable" para desbloquear la pregunta.',
    requiredInteractions: ['pipeline-run-vulnerable-dep'],
    questionId: 'lab2-sast-blocked',
    maxPoints: 10,
  },
  {
    index: 2,
    labNumber: 3,
    concept: 'Scanner ≠ Security Gate',
    title: 'Del scanner al gate: los 6 pasos',
    description: 'Un scanner detecta y reporta. Un Security Gate usa esa información para bloquear el merge. Anima el flujo completo y observa cómo cada paso es necesario.',
    interactiveKey: 'scanner-gate',
    lockHint: 'Haz clic en "Animar el flujo" y observa los 6 pasos hasta el final.',
    requiredInteractions: ['gate-animation-complete'],
    questionId: 'lab3-scanner-vs-gate',
    maxPoints: 10,
  },
  {
    index: 3,
    labNumber: 4,
    concept: 'Security Gate Explorer',
    title: 'Explora el modelo completo de SCA',
    description: 'Cada control tiene un modelo completo: Amenaza → Control → Política → Decisión → Riesgo Residual. Abre el control SCA para explorar sus limitaciones reales.',
    interactiveKey: 'controls',
    targetControl: 'sca',
    lockHint: 'Haz clic en el control "SCA — npm audit" para ver su modelo completo.',
    requiredInteractions: ['control-sca-opened'],
    questionId: 'lab4-sca-limitation',
    maxPoints: 8,
  },
  {
    index: 4,
    labNumber: 5,
    concept: 'GITHUB_TOKEN · Least Privilege',
    title: 'Radio de impacto de una Action comprometida',
    description: 'Alterna entre "Least Privilege" y "Permisos Excesivos". Observa cómo los permisos del workflow determinan el blast radius si una Action de terceros es comprometida.',
    interactiveKey: 'blast-radius',
    lockHint: 'Cambia al modo "Permisos Excesivos" y observa el impacto potencial.',
    requiredInteractions: ['blast-toggled-excessive'],
    questionId: 'lab5-blast-radius',
    maxPoints: 10,
  },
  {
    index: 5,
    labNumber: 6,
    concept: 'Ataque → Defensa',
    title: 'Identifica los controles primarios (16 pts)',
    description: 'Para cada amenaza, selecciona los controles que mejor la mitigan. La selección del control primario correcto otorga 8 puntos por amenaza. Evalúa ambas amenazas.',
    interactiveKey: 'threat-challenge',
    lockHint: 'Evalúa los controles para ambas amenazas presentadas.',
    requiredInteractions: ['threat-vuln-npm', 'threat-compromised-action'],
    questionId: null,
    threatIds: ['vulnerable-npm', 'compromised-action'],
    maxPoints: 16,
  },
  {
    index: 6,
    labNumber: 7,
    concept: 'Secure Coding · DOM XSS',
    title: 'textContent vs innerHTML — demo en vivo',
    description: 'Usa el botón "Probar XSS" e intenta inyectar HTML. Observa cómo textContent neutraliza el vector sin parsear el contenido como HTML.',
    interactiveKey: 'xss-demo',
    lockHint: 'Haz clic en "Probar XSS" para ver la protección de textContent en acción.',
    requiredInteractions: ['xss-btn-clicked'],
    questionId: 'lab7-textcontent',
    maxPoints: 10,
  },
  {
    index: 7,
    labNumber: 8,
    concept: 'Threat Modeling · Trust Boundaries',
    title: 'Arquitectura y fronteras de confianza',
    description: 'Haz clic en al menos 3 zonas del diagrama de arquitectura. Observa los activos, amenazas y controles de cada frontera de confianza.',
    interactiveKey: 'architecture',
    lockHint: 'Explora al menos 3 zonas: Desarrollador, Runner y Despliegue.',
    requiredInteractions: ['arch-zone-dev', 'arch-zone-runner', 'arch-zone-deploy'],
    questionId: 'lab8-architecture',
    maxPoints: 10,
  },
  {
    index: 8,
    labNumber: 9,
    concept: 'Referencia Técnica',
    title: 'Matriz de controles de seguridad',
    description: 'Filtra la matriz por categoría y observa las decisiones de cada control. Cuenta cuántos controles tienen una decisión que incluye BLOCK.',
    interactiveKey: 'matrix',
    lockHint: 'Filtra la matriz usando al menos uno de los botones de categoría.',
    requiredInteractions: ['matrix-filter-used'],
    questionId: 'lab9-block-controls',
    maxPoints: 10,
  },
  {
    index: 9,
    labNumber: 10,
    concept: 'Secret Scanning · Síntesis',
    title: 'Síntesis final: secreto detectado',
    description: 'Ejecuta el escenario "Secreto Detectado". Observa cómo Push Protection bloquea el push antes de que el secreto llegue al historial del repositorio.',
    interactiveKey: 'pipeline',
    scenarioToRun: 'secret-detected',
    lockHint: 'Ejecuta el escenario "Secreto Detectado" para desbloquear la pregunta final.',
    requiredInteractions: ['pipeline-run-secret-detected'],
    questionId: 'lab10-synthesis',
    maxPoints: 8,
  },
  {
    index: 10,
    labNumber: 11,
    concept: 'Incident Response · Cadena de Ataque',
    title: 'Responde al incidente: 4 fases, 1 pipeline comprometido',
    description: 'Un equipo sufrió un ataque en cadena que comprometió su pipeline de CI/CD. Analiza cada fase del ataque, identifica el control que falló en cada paso y sintetiza la defensa.',
    interactiveKey: 'incident-timeline',
    lockHint: 'Analiza las 4 fases del ataque e identifica el control que falló en cada una.',
    requiredInteractions: ['incident-phase-1-done', 'incident-phase-2-done', 'incident-phase-3-done', 'incident-phase-4-done'],
    questionId: 'lab11-kill-chain',
    maxPoints: 0,
  },
];
