/**
 * Definición de escenarios del pipeline y lógica de simulación.
 * La animación real ocurre en el DOM (index.html); este módulo produce
 * los datos que el UI consume y los tests verifican.
 */
export const STAGE_DEFINITIONS = [
  { id: 'evento',   label: 'Evento PR',    icon: '⚡' },
  { id: 'calidad',  label: 'Calidad',      icon: '🔍' },
  { id: 'pruebas',  label: 'Pruebas',      icon: '🧪' },
  { id: 'sca',      label: 'SCA',          icon: '🔒' },
  { id: 'sast',     label: 'SAST',         icon: '🛡️' },
  { id: 'revision', label: 'Revisión',     icon: '👁️' },
  { id: 'merge',    label: 'Merge',        icon: '🔀' },
  { id: 'deploy',   label: 'Deploy',       icon: '🚀' },
];

export const SCENARIOS = {
  'healthy': {
    name: 'Construcción Exitosa',
    description: 'Todos los controles pasan. El pipeline completa el ciclo completo hasta producción.',
    stages: {
      evento:   { result: 'PASSED' },
      calidad:  { result: 'PASSED' },
      pruebas:  { result: 'PASSED' },
      sca:      { result: 'PASSED' },
      sast:     { result: 'PASSED' },
      revision: { result: 'PASSED' },
      merge:    { result: 'PASSED' },
      deploy:   { result: 'PASSED' },
    },
    insight: 'Pipeline verde significa que los controles configurados no detectaron condiciones de fallo. No significa que el software esté libre de vulnerabilidades.',
    discussion: '¿Qué demuestra realmente un pipeline verde?',
    logs: [
      '[EVENT] pull_request abierto desde feature/demo hacia main',
      '[RUNNER] ubuntu-latest asignado y preparado',
      '[QUALITY] npm ci — instalando dependencias desde package-lock.json',
      '[QUALITY] ESLint ejecutándose sobre src/',
      '[QUALITY] ✓ Sin errores de lint',
      '[TEST] Ejecutando suite de pruebas con Vitest',
      '[TEST] ✓ 8 pruebas pasadas en 0.42s',
      '[SCA] npm audit --audit-level=high',
      '[SCA] ✓ Sin vulnerabilidades HIGH o CRITICAL',
      '[SAST] CodeQL inicializado para javascript-typescript',
      '[SAST] Análisis de flujo de datos completado',
      '[SAST] ✓ Sin hallazgos de alta severidad',
      '[REVIEW] ✓ Aprobación requerida satisfecha',
      '[MERGE] ✓ Required checks satisfechos — merge permitido',
      '[DEPLOY] Publicando artefacto en GitHub Pages',
      '[DEPLOY] ✓ Despliegue completado exitosamente',
    ],
  },

  'lint-failure': {
    name: 'Fallo de Lint',
    description: 'ESLint detecta un error de calidad. El Quality Gate detiene el pipeline.',
    failAt: 'calidad',
    finding: {
      severity: 'QUALITY',
      title: 'Error de calidad detectado',
      message: "Variable declarada pero no utilizada: 'tempVar'",
      rule: 'no-unused-vars',
      file: 'src/app.js:12',
      control: 'ESLint',
      policy: 'Errores de lint = FAIL',
      decision: 'BLOQUEADO',
      residualRisk: 'Este es principalmente un Quality Gate. Algunas reglas de lint tienen implicaciones de seguridad (no-eval, no-implied-eval), pero no todas.',
    },
    stages: {
      evento:   { result: 'PASSED' },
      calidad:  { result: 'FAILED' },
      pruebas:  { result: 'BLOCKED' },
      sca:      { result: 'BLOCKED' },
      sast:     { result: 'BLOCKED' },
      revision: { result: 'BLOCKED' },
      merge:    { result: 'BLOCKED' },
      deploy:   { result: 'BLOCKED' },
    },
    insight: 'El Quality Gate detuvo el pipeline. Las etapas posteriores están BLOQUEADAS porque dependen del job de calidad. Pregunta clave: ¿es ESLint un Security Gate?',
    discussion: '¿En qué se diferencia un Quality Gate de un Security Gate?',
    logs: [
      '[EVENT] pull_request abierto desde feature/demo hacia main',
      '[RUNNER] ubuntu-latest asignado',
      '[QUALITY] npm ci — instalando dependencias desde package-lock.json',
      "[QUALITY] ESLint ejecutándose sobre src/",
      "[QUALITY] ✗ src/app.js:12  error  'tempVar' está declarada pero no es utilizada  no-unused-vars",
      '[QUALITY] ✗ 1 problema encontrado (1 error, 0 advertencias)',
      '[QUALITY] Pipeline detenido. Exit code: 1',
      '[TEST] ⛔ BLOQUEADO — el job "quality" no pasó (needs: quality)',
      '[SCA] ⛔ BLOQUEADO',
      '[SAST] ⛔ BLOQUEADO',
      '[MERGE] ⛔ BLOQUEADO — Required check "quality" falló',
    ],
  },

  'test-failure': {
    name: 'Fallo de Pruebas',
    description: 'El comportamiento esperado cambió pero los tests no fueron actualizados.',
    failAt: 'pruebas',
    finding: {
      severity: 'TEST',
      title: 'Regresión funcional detectada',
      message: 'generateGreeting("Eddy") retornó un valor inesperado',
      expected: '¡Hola, Eddy! Bienvenido al laboratorio de pipeline seguro.',
      received: 'Hello Eddy! Welcome to the secure pipeline lab.',
      control: 'Pruebas Automatizadas (Vitest)',
      policy: 'Test fallido = FAIL',
      decision: 'BLOQUEADO',
      residualRisk: 'Los tests solo detectan lo que explícitamente verifican. El comportamiento no cubierto no se detecta.',
    },
    stages: {
      evento:   { result: 'PASSED' },
      calidad:  { result: 'PASSED' },
      pruebas:  { result: 'FAILED' },
      sca:      { result: 'BLOCKED' },
      sast:     { result: 'BLOCKED' },
      revision: { result: 'BLOCKED' },
      merge:    { result: 'BLOCKED' },
      deploy:   { result: 'BLOCKED' },
    },
    insight: 'Las pruebas detectaron una regresión funcional. Un test exitoso no demuestra seguridad — solo valida el comportamiento dentro del alcance de los tests escritos.',
    discussion: '¿Una prueba exitosa demuestra que el software es seguro?',
    logs: [
      '[EVENT] pull_request abierto desde feature/update-greeting hacia main',
      '[RUNNER] ubuntu-latest asignado',
      '[QUALITY] ✓ ESLint sin errores',
      '[TEST] Ejecutando suite de pruebas con Vitest',
      '[TEST] ✗ FAIL  tests/app.test.js > generateGreeting > saluda por nombre',
      "[TEST] ✗ Expected: '¡Hola, Eddy! Bienvenido al laboratorio de pipeline seguro.'",
      "[TEST] ✗ Received: 'Hello Eddy! Welcome to the secure pipeline lab.'",
      '[TEST] ✗ 1 prueba fallida de 8 | 7 pruebas pasadas',
      '[TEST] Pipeline detenido. Exit code: 1',
      '[SCA] ⛔ BLOQUEADO — el job "test" no pasó',
      '[MERGE] ⛔ BLOQUEADO — Required check "test" falló',
    ],
  },

  'vulnerable-dependency': {
    name: 'Dependencia Vulnerable',
    description: 'SCA detecta una vulnerabilidad HIGH en una dependencia del proyecto.',
    failAt: 'sca',
    finding: {
      severity: 'HIGH',
      title: 'Vulnerabilidad conocida detectada',
      package: 'demo-package@1.0.0',
      cve: 'CVE-DEMO-2024-0001',
      message: 'Prototype Pollution via manipulación de __proto__',
      control: 'SCA — npm audit',
      policy: 'Severidad HIGH o CRITICAL = BLOCK',
      decision: 'BLOQUEADO',
      residualRisk: 'Vulnerabilidades zero-day y paquetes maliciosos sin CVE registrado no son detectados por este control.',
    },
    stages: {
      evento:   { result: 'PASSED' },
      calidad:  { result: 'PASSED' },
      pruebas:  { result: 'PASSED' },
      sca:      { result: 'FAILED' },
      sast:     { result: 'BLOCKED' },
      revision: { result: 'BLOCKED' },
      merge:    { result: 'BLOCKED' },
      deploy:   { result: 'BLOCKED' },
    },
    insight: 'Esto es un Security Gate. npm audit detectó la vulnerabilidad (scanner). La política HIGH=FAIL convirtió ese hallazgo en una decisión de bloqueo (gate). El merge queda bloqueado porque el required check falló.',
    discussion: '¿Qué ocurre con una vulnerabilidad zero-day que aún no está en ninguna base de datos?',
    logs: [
      '[EVENT] pull_request abierto desde feature/add-demo-package hacia main',
      '[RUNNER] ubuntu-latest asignado',
      '[QUALITY] ✓ ESLint sin errores',
      '[TEST] ✓ 8 pruebas pasadas',
      '[SCA] npm audit --audit-level=high',
      '[SCA] ✗ Vulnerabilidad encontrada en el árbol de dependencias',
      '[SCA] ✗ Paquete: demo-package@1.0.0',
      '[SCA] ✗ Severidad: HIGH | CVE: CVE-DEMO-2024-0001',
      '[SCA] ✗ Descripción: Prototype Pollution via __proto__ manipulation',
      '[SCA] ✗ Política aplicada: HIGH >= threshold → FAIL',
      '[SCA] Pipeline detenido. Exit code: 1',
      '[SAST] ⛔ BLOQUEADO',
      '[MERGE] ⛔ BLOQUEADO — Required check "security" falló',
    ],
  },

  'sast-finding': {
    name: 'Hallazgo SAST',
    description: 'CodeQL detecta un flujo de datos potencialmente inseguro en el código.',
    failAt: 'sast',
    finding: {
      severity: 'HIGH',
      title: 'Flujo de datos potencialmente inseguro',
      rule: 'js/xss',
      message: 'Operación DOM potencialmente insegura detectada por análisis estático',
      source: 'Entrada controlada por el usuario (src/demo.js:38)',
      sink: 'innerHTML (src/demo.js:45)',
      control: 'SAST — CodeQL',
      policy: 'Hallazgo de alta severidad genera alerta en GitHub Security',
      decision: 'BLOQUEADO',
      residualRisk: 'SAST puede producir falsos positivos y falsos negativos. Los problemas de diseño y lógica de negocio generalmente no son detectados.',
    },
    stages: {
      evento:   { result: 'PASSED' },
      calidad:  { result: 'PASSED' },
      pruebas:  { result: 'PASSED' },
      sca:      { result: 'PASSED' },
      sast:     { result: 'FAILED' },
      revision: { result: 'BLOCKED' },
      merge:    { result: 'BLOCKED' },
      deploy:   { result: 'BLOCKED' },
    },
    insight: 'El SAST analiza el código sin ejecutarlo. Busca flujos de datos peligrosos desde fuentes (entrada del usuario) hacia sumideros (innerHTML). Los resultados dependen del query pack, el lenguaje y la estructura del código.',
    discussion: '¿Puede el SAST detectar todas las vulnerabilidades? ¿Qué son falsos positivos y falsos negativos?',
    logs: [
      '[EVENT] pull_request abierto desde feature/demo hacia main',
      '[RUNNER] ubuntu-latest asignado',
      '[QUALITY] ✓ ESLint sin errores',
      '[TEST] ✓ 8 pruebas pasadas',
      '[SCA] ✓ Sin vulnerabilidades HIGH o CRITICAL',
      '[SAST] Inicializando CodeQL para javascript-typescript',
      '[SAST] Construyendo modelo de código...',
      '[SAST] Ejecutando queries de seguridad...',
      '[SAST] ✗ Hallazgo: js/xss | Severidad: HIGH',
      '[SAST] ✗ Origen (source): Entrada del usuario — src/demo.js:38',
      '[SAST] ✗ Destino (sink): innerHTML — src/demo.js:45',
      '[SAST] ✗ Regla: Potential DOM-based Cross-Site Scripting',
      '[SAST] Alerta de seguridad creada en GitHub Security',
      '[REVISION] ⛔ BLOQUEADO — alerta de CodeQL pendiente de resolución',
      '[MERGE] ⛔ BLOQUEADO — Required check "CodeQL" falló',
    ],
  },

  'secret-detected': {
    name: 'Secreto Detectado',
    description: 'Secret Scanning detecta un token antes de que llegue al historial del repositorio.',
    failAt: 'evento',
    finding: {
      severity: 'CRITICAL',
      title: 'Credencial detectada en el código',
      type: 'GitHub Personal Access Token',
      message: 'Token detectado en el contenido del commit',
      file: 'config/settings.js',
      line: 3,
      control: 'Secret Scanning / Push Protection',
      policy: 'Secreto detectado → push bloqueado',
      decision: 'BLOQUEADO — push rechazado',
      residualRisk: 'Secretos en formatos no reconocidos pueden no ser detectados. El token detectado debe revocarse inmediatamente aunque el push haya sido bloqueado.',
    },
    stages: {
      evento:   { result: 'FAILED' },
      calidad:  { result: 'BLOCKED' },
      pruebas:  { result: 'BLOCKED' },
      sca:      { result: 'BLOCKED' },
      sast:     { result: 'BLOCKED' },
      revision: { result: 'BLOCKED' },
      merge:    { result: 'BLOCKED' },
      deploy:   { result: 'BLOCKED' },
    },
    insight: 'Push Protection bloqueó el push antes de que el secreto llegara al historial. Un secreto en Git persiste incluso si el archivo es eliminado en un commit posterior — el historial es permanente.',
    discussion: '¿Por qué un secreto en el historial de Git es tan difícil de "eliminar" de forma efectiva?',
    logs: [
      '[EVENT] git push origin feature/config desde workstation',
      '[GITHUB] Evaluando commits para secretos conocidos...',
      '[SECRET-SCANNING] ✗ Secreto detectado: GitHub Personal Access Token',
      '[SECRET-SCANNING] ✗ Archivo: config/settings.js | Línea: 3',
      '[SECRET-SCANNING] ✗ Push Protection: push RECHAZADO',
      '[SECRET-SCANNING] Acción requerida: revocar el token inmediatamente en GitHub Settings',
      '[EVENT] ⛔ Push rechazado — el secreto no llegó al repositorio',
      '[QUALITY] ⛔ BLOQUEADO — pull_request no fue creado',
      '[MERGE] ⛔ BLOQUEADO',
    ],
  },

  'review-rejected': {
    name: 'Revisión Rechazada',
    description: 'Todos los checks automatizados pasan, pero el revisor humano detecta un problema de diseño.',
    failAt: 'revision',
    finding: {
      severity: 'REVIEW',
      title: 'Problema de diseño detectado en revisión',
      message: 'El cambio expone datos de usuario sin validación adecuada del lado del servidor',
      reviewer: 'Revisor de seguridad del equipo',
      comment: 'Los scanners automatizados no detectaron este problema de diseño lógico. Se requiere rediseño antes del merge.',
      control: 'Revisión de Código',
      policy: 'Aprobación requerida — PR requiere cambios antes del merge',
      decision: 'BLOQUEADO',
      residualRisk: 'La fatiga del revisor y el error humano persisten como riesgos incluso con revisión obligatoria.',
    },
    stages: {
      evento:   { result: 'PASSED' },
      calidad:  { result: 'PASSED' },
      pruebas:  { result: 'PASSED' },
      sca:      { result: 'PASSED' },
      sast:     { result: 'PASSED' },
      revision: { result: 'FAILED' },
      merge:    { result: 'BLOCKED' },
      deploy:   { result: 'BLOCKED' },
    },
    insight: 'Todos los controles automatizados pasaron — el pipeline era verde hasta la revisión humana. El revisor identificó un problema de diseño que los scanners no pueden detectar. Los controles automatizados y la revisión humana son complementarios.',
    discussion: '¿Qué pueden detectar los revisores humanos que los scanners automáticos no pueden?',
    logs: [
      '[EVENT] pull_request abierto desde feature/user-data hacia main',
      '[RUNNER] ubuntu-latest asignado',
      '[QUALITY] ✓ ESLint sin errores',
      '[TEST] ✓ 8 pruebas pasadas',
      '[SCA] ✓ Sin vulnerabilidades HIGH o CRITICAL',
      '[SAST] ✓ Sin hallazgos de alta severidad',
      '[REVIEW] Revisión solicitada al equipo de seguridad',
      '[REVIEW] ✗ Cambios solicitados por revisor de seguridad',
      '[REVIEW] ✗ Comentario: "El cambio expone datos de usuario sin validación adecuada."',
      '[REVIEW] ✗ Los controles automatizados no detectaron este problema de diseño',
      '[MERGE] ⛔ BLOQUEADO — revisión pendiente: se requieren cambios antes del merge',
    ],
  },
};

export function runPipelineScenario(scenarioId) {
  const scenario = SCENARIOS[scenarioId];
  if (!scenario) return null;

  const failedStage = scenario.failAt ? scenario.stages[scenario.failAt] : null;

  return {
    id: scenarioId,
    name: scenario.name,
    description: scenario.description,
    stages: scenario.stages,
    logs: scenario.logs,
    insight: scenario.insight,
    discussion: scenario.discussion,
    finding: (failedStage && scenario.finding) ? scenario.finding : null,
  };
}
